blueprint:
  name: Motion Sensor(s) Controlling Mult Light(s) with Brightness and Time Constraints
  author: wesmannmsu
  description: "Control multiple lights based on motion sensors with brightness adjustment."
  domain: automation
  input:
    motion_sensors:
      name: Motion Sensors
      description: "List of motion sensors."
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    lights:
      name: Lights
      description: "Lights to control."
      selector:
        entity:
          domain: light
          multiple: true
    start_time:
      name: Start Time
      description: "Time when the automation can start triggering."
      default: "00:00:00"
      selector:
        time: {}
    end_time:
      name: End Time
      description: "Time when the automation stops triggering."
      default: "23:59:59"
      selector:
        time: {}
    brightness:
      name: Brightness
      description: "Brightness level for the lights."
      default: 100
      selector:
        number:
          min: 1
          max: 255
          unit_of_measurement: "%"

mode: restart
trigger:
  - platform: state
    entity_id: !input motion_sensors
    to: "on"

condition:
  - condition: time
    after: !input start_time
    before: !input end_time

action:
  - service: light.turn_on
    target:
      entity_id: !input lights
    data:
      brightness: !input brightness
