blueprint:
  name: Multi Sensor Motion Light with Time Range and Brightness
  description: >
    Turns on one or more lights when motion is detected on one or more sensors.
    Optionally only activates during a specific time range and allows setting brightness.
  domain: automation
  input:
    motion_sensors:
      name: Motion Sensor(s)
      description: "Which motion sensor(s) to use to trigger the light."
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
      multiple: true
    light_entities:
      name: Light(s)
      description: "Which light(s) to turn on."
      selector:
        target:
          entity:
            domain: light
      multiple: true
    no_motion_wait_time:
      name: "No Motion Wait Time"
      description: "How long to wait after the last motion detection before turning off the light(s)."
      default: 120
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
    time_range_start:
      name: Time Range Start (Optional)
      description: "Start time for the automation to be active. Leave empty for always active."
      default: ""
      selector:
        time: {}
      advanced: true
    time_range_end:
      name: Time Range End (Optional)
      description: "End time for the automation to be active. Leave empty for always active."
      default: ""
      selector:
        time: {}
      advanced: true
    brightness_level:
      name: Brightness Level (Optional)
      description: "Set the brightness level (1-100%) when lights turn on. Leave empty for default brightness."
      default: ""
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider
      advanced: true

# Trigger: Motion detected on any of the selected motion sensors
trigger:
  - platform: state
    entity_id: !input motion_sensors
    to: "on"

# Condition: Optional Time Range
condition:
  - condition: and
    conditions:
      - condition: or # Check if EITHER time range is NOT defined (always active) OR if current time is within range
        conditions:
          - condition: template
            value_template: "{{ not time_range_start or not time_range_end }}" # Time range NOT defined (always active)
          - condition: time
            after: !input time_range_start
            before: !input time_range_end
      - condition: trigger
        id: motion # Ensure the trigger is motion

# Action: Turn on the lights and then turn them off after a delay
action:
  - service: light.turn_on
    target: !input light_entities
    data_template:
      {% if brightness_level %}
      brightness_pct: "{{ brightness_level }}"
      {% endif %}
  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_sensors
        to: "off"
        for:
          seconds: !input no_motion_wait_time
  - service: light.turn_off
    target: !input light_entities
    data: {}
mode: restart
</code>
