blueprint:
  name: Motion Light with Multiple Sensors and Lux Condition (Improved)
  description: >
    Turns on/off a light based on multiple motion sensors and a lux threshold.
    Includes improved lux handling to prevent unnecessary light turn-offs 
    during the delay period.

  domain: automation
  input:
    sensors:
      name: Motion Sensors
      description: List of motion sensors that will trigger the light.
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    lights:
      name: Lights to Control
      description: The lights to turn on/off when motion is detected.
      selector:
        entity:
          domain: light
          multiple: true
    delay:
      name: Delay before turning off the lights (seconds)
      description: >
        How long to wait before turning off the lights when no motion is detected.
        Lights will remain on during this delay even if lux conditions change.
      default: 120
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: seconds
    mode:
      name: Trigger Mode
      description: How to trigger the lights when motion is detected.
      default: 'restart'
      selector:
        select:
          options:
            - single
            - restart
            - queued
            - parallel
    lux_sensor:
      name: Lux Sensor
      description: The sensor to check for ambient light level.
      selector:
        entity:
          domain: sensor
    lux_threshold:
      name: Lux Threshold
      description: >
        The minimum lux level below which the lights will turn on initially.
        Subsequent lux changes within the delay period will be ignored.
      default: 50
      selector:
        number:
          min: 0
          unit_of_measurement: lx

trigger:
  - platform: state
    entity_id: !input 'sensors' 
    to: 'on'  # Trigger when any motion sensor turns on

condition:
  - condition: template
    value_template: >-
      {{ states.{{ input.lux_sensor }}|float < input.lux_threshold 
          or states.helper.initial_lux_trigger == 'true' }} 
      # Check if lux is below threshold OR lights were initially turned on due to lux

action:
  - service: homeassistant.turn_on 
    entity_id: helper.initial_lux_trigger 
    # Turn on the helper entity to indicate initial lux-based trigger

  - service: light.turn_on 
    target:
      entity_id: !input 'lights' 
    # Turn on the specified lights

  - delay:
    seconds: !input 'delay' 
    # Wait for the specified delay period

  - service: homeassistant.turn_off 
    entity_id: helper.initial_lux_trigger 
    # Turn off the helper entity after delay

  - service: light.turn_off 
    target:
      entity_id: !input 'lights' 
    # Turn off the specified lights

mode: !input 'mode'
